// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu3jIZ_UyrO5JDG6q4qPayXyP7YX09Qmw',
    appId: '1:994857903052:web:02508058863c6d35a77369',
    messagingSenderId: '994857903052',
    projectId: 'test2practice-b1b34',
    authDomain: 'test2practice-b1b34.firebaseapp.com',
    storageBucket: 'test2practice-b1b34.firebasestorage.app',
    measurementId: 'G-RPBGZ6LSF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx2-KIgKKeN7EEl7B0e7AHcoV0wVJDllQ',
    appId: '1:994857903052:android:19ccec86f997be92a77369',
    messagingSenderId: '994857903052',
    projectId: 'test2practice-b1b34',
    storageBucket: 'test2practice-b1b34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ9VqSgAKlweIp0pYfxBaF7KBqx5oNUxc',
    appId: '1:994857903052:ios:ae067c8cb181943da77369',
    messagingSenderId: '994857903052',
    projectId: 'test2practice-b1b34',
    storageBucket: 'test2practice-b1b34.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ9VqSgAKlweIp0pYfxBaF7KBqx5oNUxc',
    appId: '1:994857903052:ios:ae067c8cb181943da77369',
    messagingSenderId: '994857903052',
    projectId: 'test2practice-b1b34',
    storageBucket: 'test2practice-b1b34.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu3jIZ_UyrO5JDG6q4qPayXyP7YX09Qmw',
    appId: '1:994857903052:web:d3ac3c0bba775368a77369',
    messagingSenderId: '994857903052',
    projectId: 'test2practice-b1b34',
    authDomain: 'test2practice-b1b34.firebaseapp.com',
    storageBucket: 'test2practice-b1b34.firebasestorage.app',
    measurementId: 'G-GFCR7GWGZN',
  );
}
